server:
  servlet:
    context-path: /api
reactor:
  app:
    version: 123
    servers:
      - localhost
logging:
  # path OR file can be specified
  file: ${TMP}/reactor/test.log
  # path creates spring.log
  #  path:
  level:
    root: debug
